### ISSUE TITLE
naam veranderen

### ISSUE THREAD

**Issue by anoukbruinn** [CelinexPutte/the-client-case#2]
misschien een iets kortere naam geven, dat is wat duidelijker en scheelt weer voor ruimte
https://github.com/CelinexPutte/the-client-case/blob/2b2d2fb351348d4b245f8aac7317fac2fdb532d6/index.html#L63

**Comment by CelinexPutte** [comment]
Ik heb verschillende afbeeldingen met kaarten, dus daarom zijn de namen ietsje langer. Bedankt voor de tip, maar ik laat het zo staan.
