### ISSUE TITLE
Assets map

### ISSUE THREAD

**Issue by moonlightlizaa** [CelinexPutte/the-client-case#3]
Misschien is het handiger om de naam van "Foto_2" te veranderen naar een naam dat een betere beschrijving heeft voor de afbeelding zodat het makkelijker te vinden is.

Verder ziet het er al goed uit!

**Comment by CelinexPutte** [comment]
Gedaan, was ook nog het plan om te doen. Ik had de foto's er gewoon alvast ingezet.
