### ISSUE TITLE
Misschien geen nieuwe regel hiervoor?

### ISSUE THREAD

**Issue by Trisjan** [CelinexPutte/the-client-case#4]
https://github.com/CelinexPutte/the-client-case/blob/2b2d2fb351348d4b245f8aac7317fac2fdb532d6/index.html#L24

Ik zie dat je op veel regels de ">" op een nieuwe regel hebt gezet. Het is misschien beter als je dit op dezelfde regel zet als de laatste attribute van de html element. Het creëert een ademruimte terwijl die dingen bij elkaar horen. Voor de rest ziet je code er goed uit! Complimenten naar de rest :D

**Comment by CelinexPutte** [comment]
De extentie deed het automatie. Ik heb het nu aangepast.
