### ISSUE TITLE
div in een div

### ISSUE THREAD

**Issue by anoukbruinn** [CelinexPutte/the-client-case#5]
er staat hier een div in een div. 1 van de 2 staat er voor niks. scheelt weer ruimte :)
https://github.com/CelinexPutte/the-client-case/blob/2b2d2fb351348d4b245f8aac7317fac2fdb532d6/index.html#L91

**Comment by CelinexPutte** [comment]
Nagevraagd en het is niet fout. De extra <div> heeft als functie om het adres bij elkaar te houden.
